### ISSUE TITLE
cannot search for the city 

### ISSUE THREAD

**Issue by rashadatism** [MesseBasseProduction/MesseMap#22]
cannot search for the city

**Comment by ArthurBeaulieu** [comment]
Search results in jsonp is broken, and fix is being integrated on leaflet-search component. Will  provide a patch release as soon as fix is delivered on their side. Related issue :
https://github.com/stefanocudini/leaflet-search/issues/321

**Comment by ArthurBeaulieu** [comment]
Reverted leaflet-search library to 3.0.2 where it worked as expected, waiting to properly update this lib.
